package com.patbaumgartner.greener.core.config;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Configuration for the <a href="https://www.noureddine.org/research/joular/joularcore">
 * Joular Core</a> binary that measures CPU/GPU power of the monitored process.
 *
 * <h2>How Joular Core is used</h2> Joular Core is a native Rust binary that reads
 * hardware power counters (RAPL on Linux/Windows, {@code powermetrics} on macOS) and can
 * monitor a specific PID or application name. The plugin starts Joular Core alongside the
 * Spring Boot application, lets it record power samples to a CSV file, and then computes
 * energy = Σ(power_watts × sample_interval_s).
 *
 * <h2>Typical CLI invocation generated by this config</h2>
 *
 * <pre>
 * joularcore -p &lt;PID&gt; -c cpu -f output.csv -s
 * </pre>
 *
 * @see <a href="https://github.com/joular/joularcore">joular/joularcore on GitHub</a>
 */
public class JoularCoreConfig {

	/** Default version used when auto-downloading Joular Core. */
	public static final String DEFAULT_VERSION = "0.0.1-alpha-11";

	/**
	 * Path to the joularcore binary (may be {@code null} to trigger auto-download).
	 */
	private Path binaryPath;

	/** Version to download when {@link #binaryPath} is {@code null}. */
	private String version = DEFAULT_VERSION;

	/**
	 * Hardware component to monitor. Valid values: {@code cpu}, {@code gpu}, {@code all}.
	 */
	private String component = "cpu";

	/**
	 * Monitor a specific process by PID. Set at runtime after the application process has
	 * started.
	 */
	private Long pid;

	/**
	 * Monitor all processes matching this application name (alternative to PID). When
	 * both {@link #pid} and {@link #appName} are set, PID takes precedence.
	 */
	private String appName;

	/** Path where Joular Core writes its CSV output. */
	private Path outputCsvPath;

	/**
	 * Suppress terminal output from Joular Core (pass the {@code -s} flag). Recommended
	 * to keep plugin output readable.
	 */
	private boolean silent = true;

	/**
	 * Whether to use Joular Core also as the power backend for JoularJX (when JoularJX is
	 * enabled for method-level monitoring). Maps to {@code joular-core=true} in JoularJX
	 * {@code config.properties}.
	 */
	private boolean useWithJoularJx = false;

	/**
	 * Path to the Joular Core shared-memory ring buffer file. Only relevant when
	 * {@link #useWithJoularJx} is {@code true} and JoularJX is configured with
	 * {@code joular-core-ring-buffer=true}.
	 */
	private Path ringBufferPath;

	/**
	 * Enable VM (virtual machine) mode.
	 *
	 * <p>
	 * In VM mode Joular Core cannot read hardware power counters directly (RAPL is not
	 * accessible inside a guest VM). Instead it reads the VM's total power from a file
	 * written by the host — see {@link #vmPowerFilePath}.
	 *
	 * <p>
	 * VM mode is configured via environment variables ({@code VM_CPU_POWER_FILE} and
	 * {@code VM_CPU_POWER_FORMAT}) rather than CLI flags. Use
	 * {@link #buildVmEnvironment()} to obtain the required variables.
	 *
	 * <h2>Host-side setup</h2> The host must write the VM's instantaneous power (in
	 * Watts) to {@link #vmPowerFilePath} every second. The recommended approach is
	 * <a href="https://github.com/hubblo-org/scaphandre">Scaphandre</a> running on the
	 * KVM host. See {@code examples/vm-setup/README.md} for the full setup guide covering
	 * virtio-mem, file-export, and RAPL MSR passthrough.
	 */
	private boolean vmMode = false;

	/**
	 * Path to the file that Joular Core reads for the VM's instantaneous power (Watts).
	 * Only relevant when {@link #vmMode} is {@code true}.
	 *
	 * <p>
	 * The file must contain a single floating-point number (e.g. {@code 45.2}) and should
	 * be updated every second by the host. Mapped to the {@code VM_CPU_POWER_FILE}
	 * environment variable.
	 */
	private Path vmPowerFilePath;

	/**
	 * Extra CLI arguments appended verbatim to the joularcore invocation. Useful for
	 * flags not yet covered by explicit properties.
	 */
	private List<String> extraArgs = new ArrayList<>();

	// ---- Builder-style setters ----

	public JoularCoreConfig binaryPath(Path binaryPath) {
		this.binaryPath = binaryPath;
		return this;
	}

	public JoularCoreConfig version(String version) {
		this.version = version;
		return this;
	}

	public JoularCoreConfig component(String component) {
		this.component = component;
		return this;
	}

	public JoularCoreConfig pid(long pid) {
		this.pid = pid;
		return this;
	}

	public JoularCoreConfig appName(String appName) {
		this.appName = appName;
		return this;
	}

	public JoularCoreConfig outputCsvPath(Path outputCsvPath) {
		this.outputCsvPath = outputCsvPath;
		return this;
	}

	public JoularCoreConfig silent(boolean silent) {
		this.silent = silent;
		return this;
	}

	public JoularCoreConfig useWithJoularJx(boolean useWithJoularJx) {
		this.useWithJoularJx = useWithJoularJx;
		return this;
	}

	public JoularCoreConfig ringBufferPath(Path ringBufferPath) {
		this.ringBufferPath = ringBufferPath;
		return this;
	}

	public JoularCoreConfig vmMode(boolean vmMode) {
		this.vmMode = vmMode;
		return this;
	}

	public JoularCoreConfig vmPowerFilePath(Path vmPowerFilePath) {
		this.vmPowerFilePath = vmPowerFilePath;
		return this;
	}

	public JoularCoreConfig extraArgs(List<String> extraArgs) {
		this.extraArgs = new ArrayList<>(extraArgs);
		return this;
	}

	/**
	 * Builds the CLI argument list for launching joularcore.
	 * @param resolvedBinaryPath the actual path to the joularcore binary
	 * @return ordered list of command-line tokens
	 */
	public List<String> buildCommand(Path resolvedBinaryPath) {
		List<String> cmd = new ArrayList<>();
		cmd.add(resolvedBinaryPath.toAbsolutePath().toString());

		// When monitoring a specific PID or app, do NOT pass -c (component filter)
		// because it causes Joular Core to emit a simplified 2-column CSV that
		// omits the per-process/app power column needed by the result reader.
		boolean isProcessMonitoring = false;
		if (pid != null) {
			cmd.add("-p");
			cmd.add(String.valueOf(pid));
			isProcessMonitoring = true;
		}
		else if (appName != null && !appName.isBlank()) {
			cmd.add("-a");
			cmd.add(appName);
			isProcessMonitoring = true;
		}

		if (!isProcessMonitoring && component != null && !component.isBlank()) {
			cmd.add("-c");
			cmd.add(component);
		}

		if (outputCsvPath != null) {
			cmd.add("-f");
			cmd.add(outputCsvPath.toAbsolutePath().toString());
		}

		if (silent) {
			cmd.add("-s");
		}

		if (!extraArgs.isEmpty()) {
			cmd.addAll(extraArgs);
		}

		return cmd;
	}

	// ---- Getters ----

	public Path getBinaryPath() {
		return binaryPath;
	}

	public String getVersion() {
		return version;
	}

	public String getComponent() {
		return component;
	}

	public Long getPid() {
		return pid;
	}

	public String getAppName() {
		return appName;
	}

	public Path getOutputCsvPath() {
		return outputCsvPath;
	}

	public boolean isSilent() {
		return silent;
	}

	public boolean isUseWithJoularJx() {
		return useWithJoularJx;
	}

	public Path getRingBufferPath() {
		return ringBufferPath;
	}

	public boolean isVmMode() {
		return vmMode;
	}

	public Path getVmPowerFilePath() {
		return vmPowerFilePath;
	}

	public List<String> getExtraArgs() {
		return List.copyOf(extraArgs);
	}

	/**
	 * Builds the environment variables required for Joular Core VM mode.
	 *
	 * <p>
	 * Joular Core uses {@code VM_CPU_POWER_FILE} and {@code VM_CPU_POWER_FORMAT}
	 * environment variables (not CLI flags) to configure VM power monitoring.
	 * @return a map of environment variable names to values; empty if VM mode is disabled
	 */
	public java.util.Map<String, String> buildVmEnvironment() {
		if (!vmMode) {
			return java.util.Map.of();
		}
		var env = new java.util.HashMap<String, String>();
		if (vmPowerFilePath != null) {
			env.put("VM_CPU_POWER_FILE", vmPowerFilePath.toAbsolutePath().toString());
		}
		env.put("VM_CPU_POWER_FORMAT", "watts");
		return env;
	}

}
